services:
  app:
    build: .
    image: hirelance
    container_name: hirelance
    restart: on-failure
    ports:
      - "8080:8000"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://srv1999.hstgr.io/u825468745_hirelance_db
      - SPRING_DATASOURCE_USERNAME=u825468745_hire
      - SPRING_DATASOURCE_PASSWORD=Juas5378
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SERVER_PORT=8000
      - MAIL_HOST=smtp.sendgrid.net
      - MAIL_PORT=2525
      - MAIL_USERNAME=apikey
      - MAIL_PASSWORD=your-sendgrid-api-key  # Agregar variable de email
      - BASE_URL=http://localhost:8080  # Agregar base URL
    volumes:
      - ./uploads:/app/uploads
      - ./downloads:/app/downloads